classdef pspm_import_bids_test < pspm_testcase
% Baseline and mutation tests for pspm_import_bids.
%
% Each test works on a fresh temporary copy of the BIDS dataset.
% The baseline test compares the complete import with a stored
% reference file. Mutation tests modify only the temporary copy
% and verify the expected importer behavior.
%
% The original dataset and reference file are never modified.

properties
    base_dataset
    reference_file

    temp_root
    work_dataset
    output_dir
end

methods (TestClassSetup)
    function locate_test_data(testCase)
        repo_root = fileparts(pspm_path);

        testCase.base_dataset = fullfile( ...
            repo_root, ...
            'ImportTestData', ...
            'BIDs', ...
            'Dataset');

        testCase.reference_file = fullfile( ...
            repo_root, ...
            'ImportTestData', ...
            'BIDs', ...
            'ref', ...
            'pspm_sub-CalinetBonn01_full.mat');

        testCase.assertTrue( ...
            isfolder(testCase.base_dataset), ...
            sprintf('BIDS test dataset not found:\n%s', ...
            testCase.base_dataset));

        testCase.assertTrue( ...
            isfile(testCase.reference_file), ...
            sprintf('BIDS reference file not found:\n%s', ...
            testCase.reference_file));
    end
end

methods (TestMethodSetup)
    function create_temporary_dataset(testCase)
        testCase.temp_root = tempname;
        mkdir(testCase.temp_root);

        testCase.work_dataset = fullfile( ...
            testCase.temp_root, ...
            'Dataset');

        [copy_status, copy_message] = copyfile( ...
            testCase.base_dataset, ...
            testCase.work_dataset);

        testCase.assertTrue(copy_status, copy_message);

        testCase.output_dir = fullfile( ...
            testCase.temp_root, ...
            'output');

        mkdir(testCase.output_dir);
    end
end

methods (TestMethodTeardown)
    function remove_temporary_dataset(testCase)
        if ~isempty(testCase.temp_root) && ...
                isfolder(testCase.temp_root)
            rmdir(testCase.temp_root, 's');
        end
    end
end

methods (Test)
    function test_baseline_matches_reference(testCase)
        [sts, outfiles] = pspm_import_bids( ...
            testCase.work_dataset, ...
            testCase.output_dir);

        testCase.verifyEqual( ...
            sts, ...
            1, ...
            'The baseline BIDS import failed.');

        testCase.assertNumElements( ...
            outfiles, ...
            1, ...
            'Expected exactly one imported PsPM file.');

        actual_file = outfiles{1};

        testCase.assertTrue( ...
            isfile(actual_file), ...
            sprintf('Imported PsPM file not found:\n%s', ...
            actual_file));

        testCase.compare_with_reference( ...
            actual_file, ...
            testCase.reference_file);
    end

    function test_missing_behavioral_events_is_optional(testCase)
        physio_dir = fullfile( ...
            testCase.work_dataset, ...
            'sub-CalinetBonn01', ...
            'physio');

        events_json = fullfile( ...
            physio_dir, ...
            'sub-CalinetBonn01_task-acquisition_events.json');

        events_tsv = fullfile( ...
            physio_dir, ...
            'sub-CalinetBonn01_task-acquisition_events.tsv');

        testCase.assertTrue(isfile(events_json));
        testCase.assertTrue(isfile(events_tsv));

        delete(events_json);
        delete(events_tsv);

        [sts, outfiles] = pspm_import_bids( ...
            testCase.work_dataset, ...
            testCase.output_dir);

        testCase.verifyEqual( ...
            sts, ...
            1, ...
            ['The importer should succeed when behavioral ' ...
             'events are missing.']);

        testCase.assertNumElements( ...
            outfiles, ...
            1, ...
            'Expected exactly one imported PsPM file.');

        output_file = outfiles{1};

        testCase.assertTrue( ...
            isfile(output_file), ...
            sprintf('Imported PsPM file not found:\n%s', ...
            output_file));

        imported = load(output_file, 'data', 'infos');

        actual_types = strings(numel(imported.data), 1);

        for channel_index = 1:numel(imported.data)
            actual_types(channel_index) = string( ...
                imported.data{channel_index}.header.chantype);
        end

        expected_types = [
            "ecg"
            "scr"
            "pupil_r"
            "gaze_x_r"
            "gaze_y_r"
            "blink_r"
            "saccade_r"
            "fixation_c"
        ];

        testCase.verifyEqual( ...
            sort(actual_types), ...
            sort(expected_types), ...
            ['Unexpected channel set after removing behavioral ' ...
             'events.']);

        testCase.verifyFalse( ...
            any(actual_types == "marker"), ...
            'A marker channel was imported without behavioral events.');

        testCase.verifyNumElements( ...
            imported.data, ...
            8, ...
            'Expected eight channels without the marker channel.');

        testCase.verify_behavioral_sources_absent( ...
            imported.infos);
    end

    function test_missing_eye_start_time_skips_only_eye(testCase)
        physio_dir = fullfile( ...
            testCase.work_dataset, ...
            'sub-CalinetBonn01', ...
            'physio');

        eye_json = fullfile( ...
            physio_dir, ...
            ['sub-CalinetBonn01_task-acquisition_' ...
             'recording-eye2_physio.json']);

        testCase.assertTrue( ...
            isfile(eye_json), ...
            sprintf('Eye JSON file not found:\n%s', eye_json));

        eye_metadata = jsondecode(fileread(eye_json));

        testCase.assertTrue( ...
            isfield(eye_metadata, 'StartTime'), ...
            'The baseline eye JSON does not contain StartTime.');

        eye_metadata = rmfield(eye_metadata, 'StartTime');
        testCase.write_json(eye_json, eye_metadata);

        [sts, outfiles] = pspm_import_bids( ...
            testCase.work_dataset, ...
            testCase.output_dir);

        testCase.verifyEqual( ...
            sts, ...
            1, ...
            ['The importer should continue when the eye StartTime ' ...
             'is missing.']);

        testCase.assertNumElements( ...
            outfiles, ...
            1, ...
            'Expected exactly one imported PsPM file.');

        output_file = outfiles{1};

        testCase.assertTrue( ...
            isfile(output_file), ...
            sprintf('Imported PsPM file not found:\n%s', ...
            output_file));

        imported = load(output_file, 'data', 'infos');

        actual_types = testCase.channel_types(imported.data);

        expected_types = [
            "marker"
            "ecg"
            "scr"
        ];

        testCase.verifyEqual( ...
            sort(actual_types), ...
            sort(expected_types), ...
            ['Unexpected channel set after removing eye ' ...
             'StartTime.']);

        testCase.verifyFalse( ...
            any(startsWith(actual_types, "pupil_")), ...
            'A pupil channel was imported without eye StartTime.');

        testCase.verifyFalse( ...
            any(startsWith(actual_types, "gaze_")), ...
            'A gaze channel was imported without eye StartTime.');

        testCase.verifyFalse( ...
            any(ismember( ...
                actual_types, ...
                ["blink_c", "saccade_c", "fixation_c"])), ...
            ['Eye physioevent channels were imported without a ' ...
             'valid eye recording.']);

        testCase.verifyNumElements( ...
            imported.data, ...
            3, ...
            ['Expected marker, ECG and SCR only after rejecting ' ...
             'the eye recording.']);

        testCase.verify_eye_sources_absent(imported.infos);
    end

    function test_missing_ecg_start_time_skips_only_ecg(testCase)
        physio_dir = fullfile( ...
            testCase.work_dataset, ...
            'sub-CalinetBonn01', ...
            'physio');

        ecg_json = fullfile( ...
            physio_dir, ...
            ['sub-CalinetBonn01_task-acquisition_' ...
             'recording-ecg_physio.json']);

        testCase.assertTrue( ...
            isfile(ecg_json), ...
            sprintf('ECG JSON file not found:\n%s', ecg_json));

        ecg_metadata = jsondecode(fileread(ecg_json));

        testCase.assertTrue( ...
            isfield(ecg_metadata, 'StartTime'), ...
            'The baseline ECG JSON does not contain StartTime.');

        ecg_metadata = rmfield(ecg_metadata, 'StartTime');
        testCase.write_json(ecg_json, ecg_metadata);

        [sts, outfiles] = pspm_import_bids( ...
            testCase.work_dataset, ...
            testCase.output_dir);

        testCase.verifyEqual( ...
            sts, ...
            1, ...
            ['The importer should continue when the ECG StartTime ' ...
             'is missing.']);

        testCase.assertNumElements( ...
            outfiles, ...
            1, ...
            'Expected exactly one imported PsPM file.');

        output_file = outfiles{1};

        testCase.assertTrue( ...
            isfile(output_file), ...
            sprintf('Imported PsPM file not found:\n%s', ...
            output_file));

        imported = load(output_file, 'data', 'infos');

        actual_types = testCase.channel_types(imported.data);

        expected_types = [
            "marker"
            "scr"
            "pupil_r"
            "gaze_x_r"
            "gaze_y_r"
            "blink_r"
            "saccade_r"
            "fixation_c"
        ];

        testCase.verifyEqual( ...
            sort(actual_types), ...
            sort(expected_types), ...
            ['Unexpected channel set after removing ECG ' ...
             'StartTime.']);

        testCase.verifyFalse( ...
            any(actual_types == "ecg"), ...
            'An ECG channel was imported without ECG StartTime.');

        testCase.verifyNumElements( ...
            imported.data, ...
            8, ...
            ['Expected all baseline channels except ECG after ' ...
             'rejecting the ECG recording.']);

        testCase.verify_ecg_sources_absent(imported.infos);
    end

    function test_missing_physioevents_is_optional(testCase)
        physio_dir = fullfile( ...
            testCase.work_dataset, ...
            'sub-CalinetBonn01', ...
            'physio');

        physioevents_json = fullfile( ...
            physio_dir, ...
            ['sub-CalinetBonn01_task-acquisition_' ...
             'recording-eye2_physioevents.json']);

        physioevents_tsv = fullfile( ...
            physio_dir, ...
            ['sub-CalinetBonn01_task-acquisition_' ...
             'recording-eye2_physioevents.tsv.gz']);

        testCase.assertTrue( ...
            isfile(physioevents_json), ...
            sprintf('Physioevents JSON file not found:\n%s', ...
            physioevents_json));

        testCase.assertTrue( ...
            isfile(physioevents_tsv), ...
            sprintf('Physioevents TSV file not found:\n%s', ...
            physioevents_tsv));

        delete(physioevents_json);
        delete(physioevents_tsv);

        [sts, outfiles] = pspm_import_bids( ...
            testCase.work_dataset, ...
            testCase.output_dir);

        testCase.verifyEqual( ...
            sts, ...
            1, ...
            ['The importer should succeed when eye physioevents ' ...
             'are missing.']);

        testCase.assertNumElements( ...
            outfiles, ...
            1, ...
            'Expected exactly one imported PsPM file.');

        output_file = outfiles{1};

        testCase.assertTrue( ...
            isfile(output_file), ...
            sprintf('Imported PsPM file not found:\n%s', ...
            output_file));

        imported = load(output_file, 'data', 'infos');

        actual_types = testCase.channel_types(imported.data);

        expected_types = [
            "marker"
            "ecg"
            "scr"
            "pupil_r"
            "gaze_x_r"
            "gaze_y_r"
        ];

        testCase.verifyEqual( ...
            sort(actual_types), ...
            sort(expected_types), ...
            ['Unexpected channel set after removing eye ' ...
             'physioevents.']);

        testCase.verifyFalse( ...
            any(ismember( ...
                actual_types, ...
                ["blink_c", "saccade_c", "fixation_c"])), ...
            ['Eye physioevent channels were imported although ' ...
             'their source files are missing.']);

        testCase.verifyNumElements( ...
            imported.data, ...
            6, ...
            ['Expected marker, ECG, SCR and three eye channels ' ...
             'without eye physioevents.']);

        testCase.verify_physioevents_sources_absent( ...
            imported.infos);
    end

    function test_missing_eye_columns_skips_only_eye(testCase)
        physio_dir = fullfile( ...
            testCase.work_dataset, ...
            'sub-CalinetBonn01', ...
            'physio');

        eye_json = fullfile( ...
            physio_dir, ...
            ['sub-CalinetBonn01_task-acquisition_' ...
             'recording-eye2_physio.json']);

        testCase.assertTrue( ...
            isfile(eye_json), ...
            sprintf('Eye JSON file not found:\n%s', eye_json));

        eye_metadata = jsondecode(fileread(eye_json));

        testCase.assertTrue( ...
            isfield(eye_metadata, 'Columns'), ...
            'The baseline eye JSON does not contain Columns.');

        eye_metadata = rmfield(eye_metadata, 'Columns');
        testCase.write_json(eye_json, eye_metadata);

        [sts, outfiles] = pspm_import_bids( ...
            testCase.work_dataset, ...
            testCase.output_dir);

        testCase.verifyEqual( ...
            sts, ...
            1, ...
            ['The importer should continue when eye Columns ' ...
             'metadata is missing.']);

        testCase.assertNumElements( ...
            outfiles, ...
            1, ...
            'Expected exactly one imported PsPM file.');

        output_file = outfiles{1};

        testCase.assertTrue( ...
            isfile(output_file), ...
            sprintf('Imported PsPM file not found:\n%s', ...
            output_file));

        imported = load(output_file, 'data', 'infos');

        actual_types = testCase.channel_types(imported.data);

        expected_types = [
            "marker"
            "ecg"
            "scr"
        ];

        testCase.verifyEqual( ...
            sort(actual_types), ...
            sort(expected_types), ...
            ['Unexpected channel set after removing eye ' ...
             'Columns metadata.']);

        testCase.verifyFalse( ...
            any(startsWith(actual_types, "pupil_")), ...
            'A pupil channel was imported without eye Columns.');

        testCase.verifyFalse( ...
            any(startsWith(actual_types, "gaze_")), ...
            'A gaze channel was imported without eye Columns.');

        testCase.verifyFalse( ...
            any(ismember( ...
                actual_types, ...
                ["blink_c", "saccade_c", "fixation_c"])), ...
            ['Eye physioevent channels were imported without a ' ...
             'valid eye recording.']);

        testCase.verifyNumElements( ...
            imported.data, ...
            3, ...
            ['Expected marker, ECG and SCR only after rejecting ' ...
             'the eye recording.']);

        testCase.verify_eye_sources_absent(imported.infos);
    end

    function test_missing_gaze_range_keeps_pupil(testCase)
        physio_dir = fullfile( ...
            testCase.work_dataset, ...
            'sub-CalinetBonn01', ...
            'physio');

        eye_json = fullfile( ...
            physio_dir, ...
            ['sub-CalinetBonn01_task-acquisition_' ...
             'recording-eye2_physio.json']);

        testCase.assertTrue( ...
            isfile(eye_json), ...
            sprintf('Eye JSON file not found:\n%s', eye_json));

        eye_metadata = jsondecode(fileread(eye_json));

        testCase.assertTrue( ...
            isfield(eye_metadata, 'GazeRange'), ...
            'The baseline eye JSON does not contain GazeRange.');

        eye_metadata = rmfield(eye_metadata, 'GazeRange');
        testCase.write_json(eye_json, eye_metadata);

        [sts, outfiles] = pspm_import_bids( ...
            testCase.work_dataset, ...
            testCase.output_dir);

        testCase.verifyEqual( ...
            sts, ...
            1, ...
            ['The importer should continue when GazeRange ' ...
             'metadata is missing.']);

        testCase.assertNumElements( ...
            outfiles, ...
            1, ...
            'Expected exactly one imported PsPM file.');

        output_file = outfiles{1};

        testCase.assertTrue( ...
            isfile(output_file), ...
            sprintf('Imported PsPM file not found:\n%s', ...
            output_file));

        imported = load(output_file, 'data', 'infos');

        actual_types = testCase.channel_types(imported.data);

        expected_types = [
            "marker"
            "ecg"
            "scr"
            "pupil_r"
            "blink_r"
            "saccade_r"
            "fixation_c"
        ];

        testCase.verifyEqual( ...
            sort(actual_types), ...
            sort(expected_types), ...
            ['Unexpected channel set after removing ' ...
             'GazeRange metadata.']);

        testCase.verifyTrue( ...
            any(actual_types == "pupil_r"), ...
            'The pupil channel should remain without GazeRange.');

        testCase.verifyFalse( ...
            any(actual_types == "gaze_x_r"), ...
            'gaze_x_r was imported without GazeRange.');

        testCase.verifyFalse( ...
            any(actual_types == "gaze_y_r"), ...
            'gaze_y_r was imported without GazeRange.');

        testCase.verifyTrue( ...
            all(ismember( ...
                ["blink_r", "saccade_r", "fixation_c"], ...
                actual_types)), ...
            ['Eye physioevent channels should remain when only ' ...
             'GazeRange is missing.']);

        testCase.verifyNumElements( ...
            imported.data, ...
            7, ...
            ['Expected all baseline channels except the two ' ...
             'gaze channels.']);

        testCase.verify_gaze_source_files_present( ...
            imported.infos);
    end
end

methods (Access = private)
    function compare_with_reference( ...
            testCase, actual_file, reference_file)

        actual = load(actual_file, 'data', 'infos');
        reference = load(reference_file, 'data', 'infos');

        testCase.assertTrue( ...
            isfield(actual, 'data') && isfield(actual, 'infos'), ...
            'The imported file does not contain data and infos.');

        testCase.assertTrue( ...
            isfield(reference, 'data') && ...
            isfield(reference, 'infos'), ...
            'The reference file does not contain data and infos.');

        testCase.verifyNumElements( ...
            actual.data, ...
            numel(reference.data), ...
            'The number of imported channels differs.');

        for channel_index = 1:numel(reference.data)
            actual_channel = actual.data{channel_index};
            reference_channel = reference.data{channel_index};

            testCase.compare_channel( ...
                actual_channel, ...
                reference_channel, ...
                channel_index);
        end

        testCase.compare_infos( ...
            actual.infos, ...
            reference.infos);
    end

    function compare_channel( ...
            testCase, actual_channel, reference_channel, channel_index)

        testCase.assertTrue( ...
            isfield(actual_channel, 'header') && ...
            isfield(actual_channel, 'data'), ...
            sprintf('Actual channel %d is incomplete.', ...
            channel_index));

        testCase.assertTrue( ...
            isfield(reference_channel, 'header') && ...
            isfield(reference_channel, 'data'), ...
            sprintf('Reference channel %d is incomplete.', ...
            channel_index));

        actual_type = string(actual_channel.header.chantype);
        reference_type = string(reference_channel.header.chantype);

        testCase.verifyEqual( ...
            actual_type, ...
            reference_type, ...
            sprintf('Channel type differs at position %d.', ...
            channel_index));

        testCase.verifyEqual( ...
            size(actual_channel.data), ...
            size(reference_channel.data), ...
            sprintf('Data size differs for channel "%s".', ...
            reference_type));

        testCase.verifyTrue( ...
            isequaln(actual_channel.data, reference_channel.data), ...
            sprintf('Data values differ for channel "%s".', ...
            reference_type));

        header_fields = { ...
            'chantype', ...
            'sr', ...
            'units', ...
            'StartTime' ...
        };

        for field_index = 1:numel(header_fields)
            field_name = header_fields{field_index};

            actual_has_field = ...
                isfield(actual_channel.header, field_name);

            reference_has_field = ...
                isfield(reference_channel.header, field_name);

            testCase.verifyEqual( ...
                actual_has_field, ...
                reference_has_field, ...
                sprintf( ...
                    'Header field "%s" differs for channel "%s".', ...
                    field_name, reference_type));

            if actual_has_field && reference_has_field
                testCase.verifyTrue( ...
                    isequaln( ...
                        actual_channel.header.(field_name), ...
                        reference_channel.header.(field_name)), ...
                    sprintf( ...
                        ['Header value "%s" differs for ' ...
                         'channel "%s".'], ...
                        field_name, reference_type));
            end
        end

        actual_has_markerinfo = ...
            isfield(actual_channel, 'markerinfo');

        reference_has_markerinfo = ...
            isfield(reference_channel, 'markerinfo');

        testCase.verifyEqual( ...
            actual_has_markerinfo, ...
            reference_has_markerinfo, ...
            sprintf( ...
                'markerinfo presence differs for channel "%s".', ...
                reference_type));

        if actual_has_markerinfo && reference_has_markerinfo
            testCase.verifyTrue( ...
                isequaln( ...
                    actual_channel.markerinfo, ...
                    reference_channel.markerinfo), ...
                sprintf( ...
                    'markerinfo differs for channel "%s".', ...
                    reference_type));
        end
    end

    function compare_infos(testCase, actual_infos, reference_infos)
        testCase.assertTrue( ...
            isfield(actual_infos, 'duration') && ...
            isfield(reference_infos, 'duration'), ...
            'infos.duration is missing.');

        testCase.verifyEqual( ...
            actual_infos.duration, ...
            reference_infos.duration, ...
            'AbsTol', ...
            1e-9, ...
            'infos.duration differs from the reference.');


        testCase.assertTrue( ...
            isfield(actual_infos, 'source') && ...
            isfield(actual_infos.source, 'file'), ...
            'Actual infos.source.file is missing.');

        testCase.assertTrue( ...
            isfield(reference_infos, 'source') && ...
            isfield(reference_infos.source, 'file'), ...
            'Reference infos.source.file is missing.');

        actual_sources = testCase.source_group_names( ...
            actual_infos.source.file, ...
            true);

        reference_sources = testCase.source_group_names( ...
            reference_infos.source.file, ...
            false);

        testCase.verifyEqual( ...
            actual_sources, ...
            reference_sources, ...
            ['The source-file groups or source filenames differ ' ...
             'from the reference.']);
    end

    function group_names = source_group_names( ...
            testCase, source_groups, require_existing_files)

        testCase.assertTrue( ...
            iscell(source_groups), ...
            'infos.source.file must be a cell array.');

        group_names = strings(numel(source_groups), 1);

        for group_index = 1:numel(source_groups)
            group = source_groups{group_index};

            testCase.assertTrue( ...
                iscell(group), ...
                sprintf( ...
                    'Source group %d must be a cell array.', ...
                    group_index));

            testCase.assertNumElements( ...
                group, ...
                2, ...
                sprintf( ...
                    ['Source group %d must contain exactly ' ...
                     'one JSON file and one TSV/TSV.GZ file.'], ...
                    group_index));

            paths = string(group(:));

            if require_existing_files
                testCase.verifyTrue( ...
                    all(isfile(paths)), ...
                    sprintf( ...
                        'Source group %d contains a missing file.', ...
                        group_index));
            end

            filenames = strings(numel(paths), 1);

            for file_index = 1:numel(paths)
                [~, name, extension] = fileparts(paths(file_index));
                filenames(file_index) = ...
                    string(name) + string(extension);
            end

            filenames = sort(filenames);
            group_names(group_index) = join(filenames, "|");
        end

        % Group order is not relevant, only group membership.
        group_names = sort(group_names);
    end

    function write_json(testCase, filepath, metadata)
        file_id = fopen(filepath, 'w');

        testCase.assertNotEqual( ...
            file_id, ...
            -1, ...
            sprintf('Could not open JSON file:\n%s', filepath));

        cleanup = onCleanup(@() fclose(file_id)); %#ok<NASGU>
        fwrite(file_id, jsonencode(metadata), 'char');
    end

    function types = channel_types(~, data)
        types = strings(numel(data), 1);

        for channel_index = 1:numel(data)
            types(channel_index) = string( ...
                data{channel_index}.header.chantype);
        end
    end

    function verify_gaze_source_files_present(testCase, infos)
        source_names = testCase.source_file_names(infos);

        eye_json = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physio.json";

        eye_tsv = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physio.tsv.gz";

        physioevents_json = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physioevents.json";

        physioevents_tsv = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physioevents.tsv.gz";

        expected_sources = [
            eye_json
            eye_tsv
            physioevents_json
            physioevents_tsv
        ];

        for source_index = 1:numel(expected_sources)
            testCase.verifyTrue( ...
                any(source_names == expected_sources(source_index)), ...
                sprintf( ...
                    ['Expected source file is missing from ' ...
                     'infos.source.file: %s'], ...
                    expected_sources(source_index)));
        end
    end

    function verify_physioevents_sources_absent(testCase, infos)
        source_names = testCase.source_file_names(infos);

        physioevents_json = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physioevents.json";

        physioevents_tsv = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physioevents.tsv.gz";

        testCase.verifyFalse( ...
            any(source_names == physioevents_json), ...
            ['Missing eye physioevents JSON is still listed in ' ...
             'infos.source.file.']);

        testCase.verifyFalse( ...
            any(source_names == physioevents_tsv), ...
            ['Missing eye physioevents TSV is still listed in ' ...
             'infos.source.file.']);
    end

    function verify_ecg_sources_absent(testCase, infos)
        source_names = testCase.source_file_names(infos);

        ecg_json = ...
            "sub-CalinetBonn01_task-acquisition_recording-ecg_physio.json";

        ecg_tsv = ...
            "sub-CalinetBonn01_task-acquisition_recording-ecg_physio.tsv.gz";

        testCase.verifyFalse( ...
            any(source_names == ecg_json), ...
            'Rejected ECG JSON is still listed in infos.source.file.');

        testCase.verifyFalse( ...
            any(source_names == ecg_tsv), ...
            'Rejected ECG TSV is still listed in infos.source.file.');
    end

    function verify_eye_sources_absent(testCase, infos)
        source_names = testCase.source_file_names(infos);

        eye_json = ...
            "sub-CalinetBonn01_task-acquisition_recording-eye2_physio.json";

        eye_tsv = ...
            "sub-CalinetBonn01_task-acquisition_recording-eye2_physio.tsv.gz";

        physioevents_json = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physioevents.json";

        physioevents_tsv = ...
            "sub-CalinetBonn01_task-acquisition_" + ...
            "recording-eye2_physioevents.tsv.gz";

        testCase.verifyFalse( ...
            any(source_names == eye_json), ...
            'Rejected eye JSON is still listed in infos.source.file.');

        testCase.verifyFalse( ...
            any(source_names == eye_tsv), ...
            'Rejected eye TSV is still listed in infos.source.file.');

        testCase.verifyFalse( ...
            any(source_names == physioevents_json), ...
            ['Eye physioevents JSON is still listed without a ' ...
             'valid eye recording.']);

        testCase.verifyFalse( ...
            any(source_names == physioevents_tsv), ...
            ['Eye physioevents TSV is still listed without a ' ...
             'valid eye recording.']);
    end

    function source_names = source_file_names(testCase, infos)
        testCase.assertTrue( ...
            isfield(infos, 'source') && ...
            isfield(infos.source, 'file'), ...
            'infos.source.file is missing.');

        source_groups = infos.source.file;

        testCase.assertTrue( ...
            iscell(source_groups), ...
            'infos.source.file must be a cell array.');

        source_names = strings(0, 1);

        for group_index = 1:numel(source_groups)
            group = source_groups{group_index};

            testCase.assertTrue( ...
                iscell(group), ...
                sprintf( ...
                    'Source group %d must be a cell array.', ...
                    group_index));

            paths = string(group(:));

            testCase.verifyTrue( ...
                all(isfile(paths)), ...
                sprintf( ...
                    'Source group %d contains a missing file.', ...
                    group_index));

            for file_index = 1:numel(paths)
                [~, name, extension] = fileparts(paths(file_index));
                source_names(end + 1, 1) = ...
                    string(name) + string(extension); %#ok<AGROW>
            end
        end
    end

    function verify_behavioral_sources_absent(testCase, infos)
        source_names = testCase.source_file_names(infos);

        behavioral_json = ...
            "sub-CalinetBonn01_task-acquisition_events.json";

        behavioral_tsv = ...
            "sub-CalinetBonn01_task-acquisition_events.tsv";

        testCase.verifyFalse( ...
            any(source_names == behavioral_json), ...
            ['The missing behavioral JSON file is still listed in ' ...
             'infos.source.file.']);

        testCase.verifyFalse( ...
            any(source_names == behavioral_tsv), ...
            ['The missing behavioral TSV file is still listed in ' ...
             'infos.source.file.']);
    end
end
end
