### Site info:
title: PsPM
tagline: A matlab suite for Psycho Physiological Modelling
description: "A matlab suite for Psycho Physiological Modelling"
baseurl: "/PsPM" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: bachlab_cog
github_username:  bachlab

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
#default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).
remote_theme: sighingnow/jekyll-gitbook
syntax_highlighter_style: colorful

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
excerpt_separator: <!-- more -->
