options = struct('overwrite', true);
model = struct('modelfile', 'model1.mat', ...
   'datafile', 'eda_file.mat', ...
   'timing', 'GLM_onsets.mat', ...
   'timeunits','seconds', ...
   'norm', 1, ...
   'modelspec', 'scr', ...
   'missing', 'missing_epochs.mat', ...
   'bf', struct('fhandle', @pspm_bf_scrf ,'args', 1));
glm = pspm_glm(model, options);
glm.stats