function helptext = pspm_cfg_help_format(funcname)
% pspm_cfg_help_format collects help text elements generated by
% pspm_help_init and combines them into a text block for the matlabbatch
% GUI
% Format: helptext = pspm_cfg_help_format(funcname)
%                funcname: PsPM function name (char)
global settings

helptext = {
    '------------------------------------------------------------------------------------------------', ...
    sprintf(...
    ['This GUI item calls the function %s. You can also call this function ', ...
     'directly. Type ''help %s'' in the command window for more information.'], funcname, funcname), ...
    '------------------------------------------------------------------------------------------------'};

if isfield(settings.help, funcname)
    if isfield(settings.help.(funcname), 'Description')
        helptext = [helptext(:); settings.help.(funcname).Description];
    end
    if isfield(settings.help.(funcname), 'References')
        helptext = [ helptext(:); ...
        '------------------------------------------------------------------------------------------------';...
        'References:'; ...
        settings.help.(funcname).References(:)];
    end
end
