function helptext = pspm_cfg_help_format(funcname, argname)
% pspm_cfg_help_format collects help text elements generated by
% pspm_help_init and combines them into a text block for the matlabbatch
% GUI
% Format: helptext = pspm_cfg_help_format(funcname, [argname])
%                funcname: PsPM function name (char)
%                argname: function argument (potentially a chain of nested
%                struct fields, e.g. 'options.overwrite')
global settings

if nargin < 2
    helptext = {
        '------------------------------------------------------------------------------------------------', ...
        sprintf(...
        ['This GUI item calls the function %s. You can also call this function ', ...
         'directly. Type ''help %s'' in the command window for more information.'], funcname, funcname), ...
        '------------------------------------------------------------------------------------------------'};
    
    if isfield(settings.help, funcname)
        if isfield(settings.help.(funcname), 'Description')
            A = settings.help.(funcname).Description;
            A = strrep(A, newline, [newline, newline]);
            A = splitlines(A);
            helptext = [helptext(:); ''; A];
        end
        if isfield(settings.help.(funcname), 'References')
            helptext = [ helptext(:); ''; ...
            '------------------------------------------------------------------------------------------------';...
            'References:'; ...
            settings.help.(funcname).References(:)];
        end
    end
else
    % this syntax allows chaining several nested structs into one argname
    evalc(sprintf('helptext = settings.help.%s.Arguments.%s;', funcname, argname));
    [startindx, endindx] = regexp(helptext, '\[\s*([^\[\]]*)\s*\]'); % thanks ChatGPT for finding the regexp
    helptext(startindx:endindx) = [];
    helptext = {helptext};
end