function app = pspm_ui_app (app)
% ● Descrition
%   pspm_ui_app handles the ui controlling elements for app designer based
%   GUI files. Details of font styles can be found in the developer's
%   guide.
% ● History
%   Written in 2022 by Teddy
%   Updated in 2024 by Teddy

%% General Settings
OS = ispc*1 + ismac*2 + (isunix-ismac)*3;
pspm_font_list = {'Segoe UI', '.AppleSystemUIFont', 'DejaVu Sans'};
pspm_font_size_list = {14, 14, 14};
pspm_font = pspm_font_list{OS};
pspm_font_size = pspm_font_size_list{OS};
pspm_layout_component_list_full = {...
  'title_quit',...
  'title_help',...
  'button_data_editor',...
  'button_data_display',...
  'button_ecg_editor',...
  'button_logo',...
  'text_attribution',...
  'button_discussion_forum',...
  'button_reference_manual',...
  'text_data_preprocessing',...
  'button_batch',...
  'text_data_preparation',...
  'button_model_review',...
  'button_quit'...
  };
pspm_layout_component_list_buttons = {...
  'button_data_editor',...
  'button_data_display',...
  'button_ecg_editor',...
  'button_discussion_forum',...
  'button_reference_manual',...
  'button_batch',...
  'button_model_review',...
  'button_quit'...
  };
update_app_struct(app, pspm_layout_component_list_full, 'FontName', pspm_font);
update_app_struct(app, pspm_layout_component_list_buttons, 'FontSize', pspm_font_size);
update_app_struct(app, pspm_layout_component_list_buttons, 'FontWeight', 'normal');
%% Window specific settings
switch app.layout.Name
  case 'pspm'
    attribution_disp_text = ['Build 03-06-2024 with MATLAB 2024a, ',...
      'The PsPM Team, University College London'];
    app.text_attribution.Text{1,1} = 'Version 7.0';
    app.text_attribution.Text{2,1} = attribution_disp_text;
end
return

function update_app_struct(app, components, field_name, value)
for i_comp = 1:length(components)
  app = setfield(app, components{i_comp}, field_name, value);
end
