function app = pspm_ui_app (app)
OS = ispc*1 + ismac*2 + (isunix-ismac)*3;
pspm_font_list = {'Segoe UI', '.AppleSystemUIFont', 'DejaVu Sans'};
pspm_font_size_list = {14, 14, 14};
pspm_font = pspm_font_list{OS};
pspm_font_size = pspm_font_size_list{OS};
pspm_layout_component_list_full = {'logo', 'attribution', 'button_open_issue',...
  'button_help', 'button_report_second_level', 'text_more', ...
  'button_data_preparation', 'button_data_preprocessing', ...
  'text_data_preprocessing', 'button_first_level_models', ...
  'button_batch', 'button_tools', 'text_tools', ...
  'button_models_for_sf', 'button_non_linear_scr_model', ...
  'text_second_level_model', 'text_first_level_models', ...
  'text_data_preparation', 'button_export_statistics', ...
  'button_contrast_manager' , 'button_review_model', ...
  'button_second_level_model', 'button_quit'};
pspm_layout_component_list_buttons = {'button_open_issue',...
  'button_help', 'button_report_second_level', ...
  'button_data_preparation', 'button_data_preprocessing', ...
  'button_first_level_models', ...
  'button_batch', 'button_tools', ...
  'button_models_for_sf', 'button_non_linear_scr_model', ...
  'button_export_statistics', ...
  'button_contrast_manager' , 'button_review_model', ...
  'button_second_level_model', 'button_quit'};
update_app_struct(app, pspm_layout_component_list_full, 'FontName', pspm_font);
update_app_struct(app, pspm_layout_component_list_buttons, 'FontSize', pspm_font_size);
update_app_struct(app, pspm_layout_component_list_buttons, 'FontWeight', 'normal');
end

function update_app_struct(app, components, field_name, value)
for i_comp = 1:length(components)
  app = setfield(app, components{i_comp}, field_name, value);
end
end