function segments = pspm_store_segment_stats(segments, seg_results, seg_eyes, channel_type)
stat_columns = {...
	[channel_type, '_SmoothSig_meanDiam'], ...
	[channel_type, '_SmoothSig_minDiam'], ...
	[channel_type, '_SmoothSig_maxDiam'], ...
	[channel_type, '_SmoothSig_missingDataPercent'], ...
	[channel_type, '_SmoothSig_sampleCount'], ...
	[channel_type, '_ValidSamples_meanDiam'], ...
	[channel_type, '_ValidSamples_minDiam'], ...
	[channel_type, '_ValidSamples_maxDiam'], ...
	[channel_type, '_ValidSamples_validPercent'], ...
	[channel_type, '_ValidSamples_sampleCount'], ...
	};
for eyestr = seg_eyes
	for colstr = stat_columns
		eyecolstr = [eyestr{1} colstr{1}];
		col = seg_results.(eyecolstr);
		for i = 1:numel(segments)
			segments{i}.(eyecolstr) = col(i);
		end
	end
end
end