function out = pspm_help_text(id)
% ● Description
%   pspm_help_text collects warning, error and help texts that are not
%   included in the function help texts.
% ● History
%   Introduced in PsPM 6.0
%   Written in 2022 and updated in 2024 by Teddy

switch id
    case 'warntext_subfolder'
        out = ['Subfolders of the PsPM directory are loaded into the Matlab ', ...
            'search path. \n',...
            'Do you want to remove these folders from ', ...
            'your Matlab search path during PsPM usage? \n', ...
            'These folders will be restored to Matlab path when PsPM ', ...
            'exits later. If not, PsPM will quit.'];
    case 'errortext_subfolder'
        out = ['PsPM cannot be started with subfolders added to Matlab ', ...
            'search path. Please re-try starting up PsPM and click Yes ', ...
            'when asked about removing subfolders.'];
    case 'warntext_spm_remove'
        % Warning text displayed when users have installed SPM or added path of SPM in Matlab search path
        out = ['A conflicting installation of SPM or the matlabbatch ', ...
            'is currently on your Matlab search path.\n', ...
            'Do you want to remove the respective directory/ies from ', ...
            'your Matlab search path during PsPM usage?\n', ...
            'These folders will be restored to Matlab path when PsPM ', ...
            'exits later. If not, PsPM will quit.'];
    case 'errortext_spm_quit'
        out =  ['PsPM cannot be started with conflicting SPM folders added ', ...
            'to Matlab search path. Please re-try starting up PsPM and ', ...
            'click Yes when asked about removing subfolders.'];
end