function pspm_text(path)
% ● Description
%   pspm_text is a system UI control function. It saves the text for GUI display. When
%   PsPM starts up, pspm_text will generate a .mat file that saves these text. When PsPM
%   GUI needs to use such text, this .mat file will be called and displayed on the GUI.
%   When PsPM quits, this .mat file will be deleted from the folder.
% ● History
%   Introduced in PsPM 6.0
%   Written in 2022 and updated in 2024 by Teddy

%% Help text used for the GUI
helptext_import_acq = ['Biopac Acknowledge (.acq) files can be imported with this ',...
                       'method. Acq files that are of a version equal to or lower ',...
                       'than 3.9.0 can be imported with the classic method.'];
helptext_import_acq_python = ['Biopac Acknowledge (.acq) files can be imported ',...
                       'with this method. Any version of acq files is supported ',...
                       'with the Python method. Please make sure python and the ', ...
                       'python package "Bioread" (recommended version 3.0.1) have ', ...
                       'been installed if python is the preferred method.'];
helptext_import_acqmat = '';
helptext_import_bioread = ['Loads mat files which have been converted using the ',...
                       'Bioread tool acq2mat. Bioread can be installed using pip ', ...
                       '(installed by python) or can be downloaded and installed ', ...
                       'manually from here https://github.com/njvack/bioread. It ', ...
                       'requires python and the python libraries "numpy" and "scipy".';
helptext_import_csv =  'Read using comma as a delimiter.'];
helptext_import_dsv =  ['Reads a file using a custom delimiter, for example a ', ...
                       'delimiter or a comma (,) would read the same as a csv'];
helptext_import_labchartmat = ['Supports the import of any original LabChart ', ...
                       '(.adicht) file. Since it uses an external library, this ', ...
                       'import is restricted to Windows systems only and does not ', ...
                       'work on any other operating system.'];
helptext_import_matlab = ['Each input file must contain a variable called data that ', ...
                       'is either a cell array of column vectors, or a data points ', ...
                       'channels matrix. The import of event markers is supported. ', ...
                       'Marker channels are assumed to be continuous if the input ', ...
                       'data is a matrix or if the input data is a cell and the ', ...
                       'given sample rate is larger than 1 Hz. A sample rate has to ', ...
                       'be specified for any type of data.'];
helptext_import_spike = '';
helptext_import_txt = ['Text files can only contain numbers (i.e. no header lines ', ...
                       'with channel names) and one data column per channel. Make ', ...
                       'sure you use the decimal point (i.e. not decimal comma as ', ...
                       'used in some non-English speaking countries). ', ...
                       'At the moment, no import of event markers is possible.'];
helptext_import_labchartmat_ext = ['Export data to Matlab format (plugin for the ', ...
                       'LabChart software, available from ', ...
                       'https://www.adinstruments.com).';]
helptext_import_labchartmat_in = '';
helptext_import_vario = '';
helptext_import_biograph = ['Export data to text format, both "Export Channel Data" ', ...
                       'and "Export Interval Data" are supported; a header is required'];
helptext_import_physlog = ['The physlog ascii file contains 6 channels with ', ...
                       'physiological measurements (Channel id 1-6): ECG1, ECG2, ', ...
                       'ECG3, ECG4, Pulse oxymeter, Respiration. Depending on your ', ...
                       'scanner settings, there are 10 trigger channels of which ', ...
                       'channel 6 marks time t of the last slice recording. After ', ...
                       'importing, a time window from t minus ', ...
                       '(#volumes )*(repetition time) seconds until t should be ', ...
                       'used for trimming or splitting of sessions to constrain ', ...
                       'data in the imported file to the EPI recording window and ', ...
                       'easier matching with experimental events from a separate ', ...
                       'source. Available trigger channels are (Channel id 1-10): ', ...
                       'Trigger ECG, Trigger PPG, Trigger Respiration, Measurement ', ...
                       '(?slice onset?), Start of scan sequence, End of scan ', ...
                       'sequence, Trigger external, Calibration, Manual start, ', ...
                       'Reference ECG Trigger.'];
helptext_import_viewpoint = 'See pspm_get_viewpoint documentation';
helptext_import_smi = 'See pspm_get_smi documentation';
helptext_import_eyelink = ['Eyelink output files (with extension *.edf) must first ', ...
                       'be converted to ASCII format (extension *.asc). This is ', ...
                       'done with the utility edf2asc.exe (normally included in the ', ...
                       'Eyelink software in <Path to Program Files>\SR Research', ...
                       '\EyeLink\EDF_Access_API\). Otherwise there is a Data ', ...
                       'viewer, available at http://www.sr-research.com/dv.html ', ...
                       '(registration needed), which installs a utility called ', ...
                       '"Visual EDF2ASC". This also allows the conversion and does ', ...
                       'not require a license. The composition of channels depends ', ...
                       'on the acquisition settings. Available channels are ', ...
                       'Pupil L, Pupil R, x L, y L, x R, y R, Blink L, Blink R, ', ...
                       'Saccade L, Saccade R. The channels will be imported ', ...
                       'according to a known data structure, therefore channel ids ', ...
                       'passed to the import function or set in the Batch will be ', ...
                       'ignored. In the PsPM file channels, which were not ', ...
                       'available in the data file, will be padded with NaN values. ', ...
                       'Additionally periods of blinks and saccades will be set to ', ...
                       'NaN during the import.'];
helptext_import_edf = '';
helptext_import_biosemi = '';
helptext_import_windaq_n = ['Windaq import written by the PsPM team. It is platform ', ...
                       'independent, thus has no requirements for ActiveX Plugins, ', ...
                       'Windows or 32bit Matlab. Imports the original acquisition ', ...
                       'files files. Up to now the import has been tested with ', ...
                       'files of the following type: Unpacked, no Hi-Res data, no ', ...
                       'Multiplexer files. A warning will be produced if the ', ...
                       'imported data-type fits one of the yet untested cases. If ', ...
                       'this is the case try to use the import provided by the ', ...
                       'manufacturer (see above).'];
helptext_import_cnt = '';
helptext_import_observer = '';
helptext_import_biotrace = '';
helptext_import_brainvision = '';
helptext_import_windaq = ['Requires an ActiveX Plugin provided by the manufacturer ', ...
                       'and contained in the subfolder Import/wdq for your ', ...
                       'convenience. This plugin only runs under 32 bit Matlab on ', ...
                       'Windows.'];
%% Warning and error text
% Warning text displayed when users have added any subfolders that shall be avoided
warntext_subfolder =  ['Subfolders of the PsPM directory are loaded into the Matlab ', ...
                       'search path. \n',...
                       'Do you want to remove these folders from ', ...
                       'your Matlab search path during PsPM usage? \n', ...
                       'These folders will be restored to Matlab path when PsPM ', ...
                       'exits later. If not, PsPM will quit.'];
errortext_subfolder = ['PsPM cannot be started with subfolders added to Matlab ', ...
                       'search path. Please re-try starting up PsPM and click Yes ', ...
                       'when asked about removing subfolders.'];
% Warning text displayed when users have been using too old version of Matlab
warntext_matlab_old = ['You are running PsPM on a Matlab version (%s) under which ', ...
                       'it has not been tested.\nIf you encounter any other error, ', ...
                       'please upgrade your Matlab installation.'];
% Warning text displayed when users have installed matlabbatch for SPM
warntext_matlabbatch =['Matlabbatch from SPM and its config folder are currently on ', ...
                       'your Matlab search path.\n', ...
                       'Do you want to remove these folders temporarily from your ', ...
                       'Matlab search path in order to avoid potential issues with ', ...
                       'matlabbatch from PsPM?'];
% Warning text displayed when users have not installed Signal Processing Toolbox
warntext_sigproc_toolbox =['Signal processing toolbox not installed. ', ...
                       'Some filters might not be implemented.'];
% Warning text displayed when users have installed SPM or added path of SPM in Matlab search path
warntext_spm_remove = ['A conflicting installation of SPM or the matlabbatch ', ...
                       'is currently on your Matlab search path.\n', ...
                       'Do you want to remove the respective directory/ies from ', ...
                       'your Matlab search path during PsPM usage?\n', ...
                       'These folders will be restored to Matlab path when PsPM ', ...
                       'exits later. If not, PsPM will quit.'];
errortext_spm_quit =  ['PsPM cannot be started with conflicting SPM folders added ', ...
                       'to Matlab search path. Please re-try starting up PsPM and ', ...
                       'click Yes when asked about removing subfolders.'];
%% Save
save(fullfile(path,'pspm_text.mat'))
return
